# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d54651da030026083fd166fa6e00f3159c040bd55ea1ec5884ff7ddd9a3dc011a90f036fb9d98273bb9c90696a2fe278ef73d14cac76f6e142352e980e8194e

test:
  secret_key_base: 48b9e79969a1b28edf45e30c1def1fb94edfbbde0221bd4d229db8253fea700da89673e0e77fad2428932be666e42dcd908d06cba1cbfa6f7bbc53d79b7599a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
